# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-11 17:25
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0003_auto_20161111_1655'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='kirrurl',
            managers=[
                ('obj_active', django.db.models.manager.Manager()),
            ],
        ),
    ]
