# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-11 17:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0005_auto_20161111_1734'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='kirrurl',
            managers=[
            ],
        ),
    ]
